"""AWS environment variable names."""

from __future__ import annotations

AWS_ROLE_ARN_ENV = "AWS_ROLE_ARN"
AWS_EXTERNAL_ID_ENV = "AWS_EXTERNAL_ID"
AWS_REGION_ENV = "AWS_REGION"
AWS_ACCESS_KEY_ID_ENV = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV = "AWS_SECRET_ACCESS_KEY"
AWS_SESSION_TOKEN_ENV = "AWS_SESSION_TOKEN"

__all__ = [
    "AWS_ACCESS_KEY_ID_ENV",
    "AWS_EXTERNAL_ID_ENV",
    "AWS_REGION_ENV",
    "AWS_ROLE_ARN_ENV",
    "AWS_SECRET_ACCESS_KEY_ENV",
    "AWS_SESSION_TOKEN_ENV",
]
