"""OpenClaw MCP environment variable names."""

from __future__ import annotations

OPENCLAW_MCP_URL_ENV = "OPENCLAW_MCP_URL"
OPENCLAW_MCP_MODE_ENV = "OPENCLAW_MCP_MODE"
OPENCLAW_MCP_COMMAND_ENV = "OPENCLAW_MCP_COMMAND"
OPENCLAW_MCP_ARGS_ENV = "OPENCLAW_MCP_ARGS"
OPENCLAW_MCP_AUTH_TOKEN_ENV = "OPENCLAW_MCP_AUTH_TOKEN"

__all__ = [
    "OPENCLAW_MCP_ARGS_ENV",
    "OPENCLAW_MCP_AUTH_TOKEN_ENV",
    "OPENCLAW_MCP_COMMAND_ENV",
    "OPENCLAW_MCP_MODE_ENV",
    "OPENCLAW_MCP_URL_ENV",
]
